### ISSUE TITLE
Should Prevent be a PureComponent?

### ISSUE THREAD

**Issue by andrefgneves** [didierfranc/react-waterfall#23]
Hi. I'm trying out having multiple stores (multiple providers and consumers) and found that changes in outer contexts don't propagate all the way through to inner consumers.

Here's a (contrived) example to better explain what I mean.
https://codesandbox.io/s/4j6z81r094

When I change the Prevent component to not be Pure, everything works as expected.
Am I missing something?

Thanks.

**Comment by didierfranc** [comment]
This has been changed in the latest release 🤔

https://github.com/didierfranc/react-waterfall/blob/master/src/index.js#L6

**Comment by elisherer** [comment]
The "error" is nesting the cosumers, we defined consumers as pure, meaning there shouldn't be any side effects from within the component. 
Maybe like redux's connect we should enable opting out (i.e `pure: false`).

**Comment by elisherer** [comment]
Apperantly, it was an issue with react-waterfall after all and it is about to be solved in the next version.
It had to do with children of components not get rendered because of the children prop being overridden.
#46 #49 
Working example (notice the API of consumer was changed)
https://codesandbox.io/s/819296qmpl

**Comment by andrefgneves** [comment]
Great, thanks.
